name: deploy to lambda
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: install serverless
        run: npm install -g serverless
      - name: deploy lambda
        run: serverless deploy --region ${{ secrets.AWS_REGION }} --aws-profile default --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}