service: MVP
provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'
functions:
  my-function:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any