service: MVP

plugins:
  - serverless-plugin-monorepo

custom:
  monorepo:
    include:
      - apps/api/**

# Service 1 configuration
api:
  service: api
  app: MVP
  stage: dev
  region: us-east-1
  provider:
    name: aws
    runtime: nodejs18.x
  functions:
    hello:
      handler: handler.hello
      events:
        - http:
            path: 
            method: get
